import { useRouter } from "next/router";
import { FormEvent, useState } from "react";
import { Box, Button, Flex, useToast } from "@chakra-ui/react";
import Head from "next/head";
import { useMutation } from "@tanstack/react-query";
import { authentication } from "../services/authentication";
import { getUser } from "../services/user";
import Cookies from "js-cookie";
import Link from "next/link";

export default function Login() {
  const router = useRouter();

  const [login, setLogin] = useState("");
  const [password, setPassword] = useState("");

  const toast = useToast();

  const authenticationQuery = useMutation(authentication);

  const getUserQuery = useMutation(getUser);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const input = {
      username: login,
      password: password,
    };

    try {
      await authenticationQuery.mutateAsync(input);
      return router.push({
        pathname: `/dashboard`,
      });
    } catch (err) {
      return toast({
        title: err.response.data.message,
        status: "error",
        duration: 2000,
        isClosable: true,
        position: "top-right",
      });
    }
  }

  return (
    <div>
      <Head>
        <title>NG - Trybe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 h-screen">
        <div className="bg-purple-900 flex justify-center items-center h-1/2 sm:h-screen lg:h-screen bg-waves bg-no-repeat bg-center bg-cover p-10">
          <div>
            <h1 className="text-white text-[40px] sm:text-[60px] lg:text-[60px] font-black">
              A CARTEIRA DA NOVA GERAÇÃO.
            </h1>
            <h2 className="text-white text-[30px] sm:text-[50px] lg:text-[50px]">
              É para todas as idades!
            </h2>
          </div>
        </div>
        <div className="bg-white flex justify-center items-center h-1/2 sm:h-screen lg:h-screen lg:bg-ng sm:bg-ng lg:bg-no-repeat lg:bg-center lg:bg-cover sm:bg-no-repeat sm:bg-center sm:bg-cover">
          <form
            className="flex flex-col gap-4 p-4 bg-ng-green rounded-2xl"
            onSubmit={handleSubmit}
          >
            <input
              type="text"
              placeholder="Login"
              className="p-4 rounded-xl"
              onChange={(event) => setLogin(event.target.value)}
            />
            <input
              type="password"
              placeholder="Password"
              className="p-4 rounded-xl"
              onChange={(event) => setPassword(event.target.value)}
            />
            <Button
              isLoading={
                authenticationQuery.isLoading || getUserQuery.isLoading
              }
              type="submit"
              colorScheme={"purple"}
              // className="w-full p-4 bg-black text-white hover:bg-black-900 rounded-2xl"
            >
              Entrar
            </Button>
            <Flex alignItems={"center"}>
              <Box fontSize={"xs"}>Ainda não faz parte da nova geração?</Box>
              <Link passHref href={"/"}>
                <Button
                  variant={"ghost"}
                  colorScheme={"purple"}
                  size={"sm"}
                  ml={2}
                >
                  SIGN UP
                </Button>
              </Link>
            </Flex>
          </form>
        </div>
      </div>
    </div>
  );
}
